[package]
name = "rusty-machine-learning"
version = "0.1.0"
authors = ["Charles Black <18634426+charlesoblack@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq="*"
num="*"
